#!/bin/bash

#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 03:00:00
#SBATCH --ntasks-per-node=64
#SBATCH --no-requeue

# type 'man sbatch' for more information and options
# this job will ask for 1 full RM node (128 cores) for 5 hours
# this job would potentially charge 640 RM SUs

#echo commands to stdout
set -x

# move to working directory
# this job assumes:
# - all input data is stored in this directory
# - all output should be stored in this directory
# - please note that groupname should be replaced by your groupname
# - username should be replaced by your username
# - path-to-directory should be replaced by the path to your directory where the executable is

module STAR

cd $PROJECT/eclip

mkdir ./STAR/genomehg38
STAR \
--runThreadN 64 \
--runMode genomeGenerate \
--genomeDir ./STAR/genomehg38/ \
--genomeFastaFiles ./STAR/hg38/hg38.fa \
--sjdbGTFfile ./STAR/hg38/hg38_refGene.gtf \
--sjdbOverhang 99

mkdir ./STAR/genomeRM
STAR \
--runThreadN 64 \
--runMode genomeGenerate \
--genomeDir ./STAR/genomeRM/ \
--genomeFastaFiles ./STAR/hg38/repbase.fasta \
