#!/bin/bash

#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 04:00:00
#SBATCH --ntasks-per-node=32
#SBATCH --no-requeue

set -x

bed=`realpath $1`
testgenome=`realpath $2`
datasetName=`realpath $3`
saveFolder=`realpath $4`

cd $PROJECT/eclip

GENOME="$PROJECT/eclip/STAR/hg38/hg38.fa"

echo "genome: " $GENOME

module load anaconda3
conda deactivate
module load anaconda3
module load bedtools
conda activate pytorch
# source ~/anaconda3/etc/profile.d/conda.sh

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 INPUTBED TESTGENOME DATASETSAVENAME FIGUREPATH"
  echo "example: $0 ./RBFOX.bed ./COVID.fasta ./test.fasta ./figures"
  exit 1
fi

bed=`realpath $1`
testgenome=`realpath $2`
datasetName=`realpath $3`
saveFolder=`realpath $4`

echo "input bed: "  $bed

echo "test genome: "  $testgenome

echo "dataset save name: "  $datasetName

echo "save figures under: " $saveFolder

# cd $PROJECTS/eclip

python ./learn/tofasta.py --bed $bed

bedtools getfasta \
-fi $GENOME \
-bed ./temp.bed > $datasetName

rm ./temp.bed

conda activate pytorch

echo "train full model"

chmod +x train.py
python ./learn/train.py --save ./learn/models -ds $datasetName -c

echo "train motif model"
chmod +x ./learn/train.py
python ./learn/train.py --save ./learn/models -ds $datasetName --model motif -c

echo "test model on genome"
chmod +x ./learn/test.py
python ./learn/test.py --save $saveFolder --model ./full.pth --testfasta $testgenome -ds $datasetName

echo "get logo"
chmod +x ./learn/drawlogo.py
python ./learn/drawlogo.py --model ./motif.pth --save $saveFolder

conda deactivate

rm ./motif.pth
rm ./full.pth
rm ./rbfox2.fa
mv figures ./output/
